@extends('layouts/main')

@section('mainClass')

<div class="w-full max-w-full mt-0 mb-6 md:mb-0">
    <div class="border-black/12.5 shadow-soft-xl relative flex min-w-0 flex-col break-words rounded-2xl border-0 border-solid bg-white bg-clip-border h-auto mb-4">
       
        <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
            <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new Load Balance Testing Web Server</h2>
            <form action="/loadTest" method="post">
                @csrf
                <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                    <div class="sm:col-span-2">
                        
                        <label for="server_address" class="block mb-2 text-sm flex items-center font-medium text-gray-900 dark:text-white">Server Address<button data-popover-target="popover-description" data-popover-placement="bottom-end" type="button">
    
                            <svg class="w-4 h-4 ms-1 text-gray-400 hover:text-gray-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20 24"><path fill-rule="evenodd" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 13V8m0 8h0m9-4a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z"/></svg>
                              
                            {{-- <svg class="w-4 h-4 ms-2 text-gray-400 hover:text-gray-500" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-8-3a1 1 0 00-.867.5 1 1 0 11-1.731-1A3 3 0 0113 8a3.001 3.001 0 01-2 2.83V11a1 1 0 11-2 0v-1a1 1 0 011-1 1 1 0 100-2zm0 8a1 1 0 100-2 1 1 0 000 2z" clip-rule="evenodd"></path></svg> --}}
                        
                        </button></label>
                        <div data-popover id="popover-description" role="tooltip" class="absolute z-50 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400">
                            <div class="p-3 space-y-2">
                                <h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
                                <p>Report helps navigate cumulative growth of community activities. Ideally, the chart should have a growing trend, as stagnating chart signifies a significant decrease of community activity.</p>
                                <h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
                                <p>For each date bucket, the all-time volume of activities is calculated. This means that activities in period n contain all activities up to period n, plus the activities generated by your community in period.</p>
                                <a href="#" class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700 hover:underline">Read more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                        </svg></a>
                            </div>
                            <div data-popper-arrow></div>
                        </div>
    
                        <input type="text" name="server_address" id="server_address" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 @error('server_address') is-invalid @enderror" placeholder="192.168.x.x OR domain.com" required="">
                        @error('server_address')
                                <div class="alert alert-danger" style="font-size: 12px; color: red;">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="w-full">
                        <label for="request_count" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Request Count</label>
                        <input type="number" name="request_count" id="request_count" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 @error('request_count') is-invalid @enderror" placeholder="Request per Second">
                        @error('request_count')
                                <div class="alert alert-danger" style="font-size: 12px; color: red;">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class="w-full">
                        <label for="connection_count" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Connection Count</label>
                        <input type="number" name="connection_count" id="connection_count" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 @error('connection_count') is-invalid @enderror" placeholder="2999">
                        @error('connection_count')
                                <div class="alert alert-danger" style="font-size: 12px; color: red;">{{ $message }}</div>
                        @enderror
                    </div>
                    <div>
                        <label for="algortima_LB" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Algoritma Load Balance</label>
                        <select id="algortima_LB" name="algortima_LB" onchange="toggleOtherInput(this);" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                            <option selected="">Select category</option>
                            <option value="round_robin">Round Robin</option>
                            <option value="weight_round_robin">Weight Round Robin</option>
                            <option value="least_connection">Least Connection</option>
                            <option value="weight_least_connection">Weight Least Connection</option>
                            <option value="no_load_balancer">No Load Balancer</option>
                            {{-- <option value="Other">Other</option> --}}
                        </select>
                    </div>
                    <div id="otherInput" style="display: none;">
                        <label for="algortima_LB" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Other Option</label>
                        <input type="text" id="algortima_LB" name="algoritma_LB" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                    </div>

                    <div>
                        <label for="field_chart" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Field Chart</label>
                        <select name="field_chart" id="field_chart" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                            <option selected="">Select Field</option>
                            <option value="field_chart1">Field Chart1</option>
                            <option value="field_chart2">Field Chart2</option>
                            <option value="field_chart3">Field Chart3</option>
                            <option value="field_chart4">Field Chart4</option>
                        </select>
                    </div>

                    <div>
                        <label for="urutan_pengukuran" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Urutan Pengukuran</label>
                        <select name="urutan_pengukuran" id="urutan_pengukuran" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500">
                            <option selected="">Select Field</option>
                            <option value="1">Pengukuran ke-1</option>
                            <option value="2">Pengukuran ke-2</option>
                            <option value="3">Pengukuran ke-3</option>
                            {{-- <option value="4">Pengukuran ke-4</option> --}}
                        </select>
                    </div>

                </div>
                <button type="submit" class="inline-flex items-center px-5 py-2.5 mt-4 sm:mt-6 text-sm font-medium text-center text-white bg-primary-700 rounded-lg focus:ring-4 focus:ring-primary-200 dark:focus:ring-primary-900 hover:bg-primary-800">
                    Add Testing
                </button>
            </form>
        </div>
        
    </div>
</div>


<div class="border-2 border-dashed rounded-lg border-gray-100 dark:border-gray-200 h-auto mb-4">
  
</div>

@push('js')

<script>
    function toggleOtherInput(selectElement) {
        var otherInput = document.getElementById('otherInput');
        if (selectElement.value === 'Other') {
            otherInput.style.display = 'block';
        } else {
            otherInput.style.display = 'none';
        }
    }
</script>

@endpush

@endsection



